### ISSUE TITLE
fix regression tests runner

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/soepy#31]
```
python regression_vault.py  --request check --num 10

Traceback (most recent call last):
  File "regression_vault.py", line 105, in <module>
    check_vault()
  File "regression_vault.py", line 70, in check_vault
    df = simulate("test.grmpy.yml")
  File "/home/peisenha/OpenSourceEconomics/soepy/soepy/python/simulate/simulate_python.py", line 13, in simulate
    model_params = read_init_file(init_file_name)
  File "/home/peisenha/OpenSourceEconomics/soepy/soepy/python/pre_processing/model_processing.py", line 10, in read_init_file
    with open(init_file_name) as y:
FileNotFoundError: [Errno 2] No such file or directory: 'test.grmpy.yml'

```

**Comment by peisenha** [comment]
This was done a part of #25
